export type UserType = {
  name?: string,
  email?: string,
  username?: string,
  password?: string,
  role?: string,
  otp?: number,
  id: number,
  address?: string,
  phone?: string,
  currentPassword?: string,
  newPassword?: string,
  active?: boolean,
  createdAt?: string,
  updatedAt?: string,
}